// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStXD_5RJNzU7-_QnUZh4Q2gqFKG9AUlk',
    appId: '1:251416681499:web:ecde879521194ea56decbe',
    messagingSenderId: '251416681499',
    projectId: 'chat-app-demo-34ed8',
    authDomain: 'chat-app-demo-34ed8.firebaseapp.com',
    databaseURL: 'https://chat-app-demo-34ed8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-demo-34ed8.firebasestorage.app',
    measurementId: 'G-FRMQVCS1XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOhMZQS-Sfz0mGNvRgcfeEDdvbYdVv2s',
    appId: '1:251416681499:android:3ebf0338cf722b4b6decbe',
    messagingSenderId: '251416681499',
    projectId: 'chat-app-demo-34ed8',
    databaseURL: 'https://chat-app-demo-34ed8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-demo-34ed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwpYRBbl0ga212GbezdHLM5lkTOiNwPmM',
    appId: '1:251416681499:ios:5a8de9241d50731b6decbe',
    messagingSenderId: '251416681499',
    projectId: 'chat-app-demo-34ed8',
    databaseURL: 'https://chat-app-demo-34ed8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-demo-34ed8.firebasestorage.app',
    iosBundleId: 'com.example.chatAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwpYRBbl0ga212GbezdHLM5lkTOiNwPmM',
    appId: '1:251416681499:ios:5a8de9241d50731b6decbe',
    messagingSenderId: '251416681499',
    projectId: 'chat-app-demo-34ed8',
    databaseURL: 'https://chat-app-demo-34ed8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-demo-34ed8.firebasestorage.app',
    iosBundleId: 'com.example.chatAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStXD_5RJNzU7-_QnUZh4Q2gqFKG9AUlk',
    appId: '1:251416681499:web:ded980dfdbbaa98f6decbe',
    messagingSenderId: '251416681499',
    projectId: 'chat-app-demo-34ed8',
    authDomain: 'chat-app-demo-34ed8.firebaseapp.com',
    databaseURL: 'https://chat-app-demo-34ed8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-demo-34ed8.firebasestorage.app',
    measurementId: 'G-63DWN9EBE3',
  );
}
